name: TriggerHappy - Discussion Moderation Tool

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  discussions: write
  contents: write

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: erstarr/TriggerHappy@v0.1
        with:
          # github_token: ${{ secrets.CROSS_REPO_TOKEN }} ---> TODO: point this at hypr's .github repo
          storage_repo: your_org/yourRepo
          config_path:  discussion_moderator/config.yml
          banned_path:  discussion_moderator/banned.yml
          strikes_path: discussion_moderator/strikes.yml

          strikes_to_ban:  5
          auto_close_regex: "(?s).*### I acknowledge that:\n\n- \[[xX]\][^\n]*\n- \[[xX]\][^\n]*\n- \[[xX]\][^\n]*.*"      
          auto_close_categories: "Bugs - CMake / Meson / Nix, Bugs - Config, Bugs - Crashes, Bugs - DRM, Bugs - Input, Bugs - IPC / Plugins, Bugs - Layout, Bugs - Other, Bugs - Performance, Bugs - Renderer, Bugs - Window management, Bugs - XWayland, Feature requests - Config, Feature requests - Layouts, Feature requests - Other, Feature requests - Protocols / Integrations, Feature requests - Renderer, Feature requests - Window management"
          strike_per_nonFormat: True